// app.js
App({
  globalData: {
    data:[{
      id:0,
      sort:1,
      title:"(HUAWEI)P30 ",
      titleTwo:"超感光徕卡三摄|逆光智美自拍",
      price:"4288.00",
      image:"/images/goods1.jpg",
      imageone:"/images/goods1-swiper01.jpg",
      imagetwo:"/images/goods1-swiper02.jpg",
      imagethree:"/images/goods1-swiper03.jpg",
      imgdetail:[{
        image:"/images/goods1-detail01.jpg",
        mode:"widthFix"
      },{
        image:"/images/goods1-detail02.jpg",
        mode:"widthFix"
      }],
      imgdeparameter:[{
        image:"/images/goods1-dpm01.jpg",
        mode:"widthFix"
      },{
        image:"/images/goods1-dpm02.jpg",
        mode:"widthFix"
      }]
    },
    {
      id:1,
      sort:1,
      title:"(HUAWEI)荣耀V20 ",
      titleTwo:"魅眼视屏4800万深感相机",
      price:"3699.00",
      image:"/images/goods2.jpg",
      imageone:"/images/goods2-swiper01.jpg",
      imagetwo:"/images/goods2-swiper02.jpg",
      imagethree:"/images/goods2-swiper03.jpg",
      imgdetail:[{
        image:"/images/goods2-detail01.jpg",
        mode:"widthFix"
      },{
        image:"/images/goods2-detail02.jpg",
        mode:"widthFix"
      }
    ],
      imgdeparameter:[{
        image:"/images/goods2-dpm01.jpg",
        mode:"widthFix"
      },{
        image:"/images/goods2-dpm02.jpg",
        mode:"widthFix"
      }]
    },
    {
      id:2,
      sort:2,
      title:"IE80S入耳式监听耳机 ",
      titleTwo:"森海塞尔HiFi音乐耳机",
      price:"2399.00",
      image:"/images/goods3.jpg",
      imageone:"/images/goods3-swiper01.jpg",
      imagetwo:"/images/goods3-swiper02.jpg",
      imagethree:"/images/goods3-swiper03.jpg",
      imgdetail:[{
        image:"/images/goods3-detail01.jpg",
        mode:"widthFix"
      },{
        image:"/images/goods3-detail02.jpg",
        mode:"widthFix"
      }
    ],
      imgdeparameter:[{
        image:"/images/goods3-dpm01.jpg",
        mode:"widthFix"
      },{
        image:"/images/goods3-dpm02.jpg",
        mode:"widthFix"
      }]
    },
    {
      id:3,
      sort:2,
      title:"IE60入耳式HiFi耳机 ",
      titleTwo:"森海塞尔HiFi音乐耳机",
      price:"799.00",
      image:"/images/goods4.jpg",
      imageone:"/images/goods4-swiper01.jpg",
      imagetwo:"/images/goods4-swiper02.jpg",
      imagethree:"/images/goods4-swiper03.jpg",
      imgdetail:[{
        image:"/images/goods4-detail01.jpg",
        mode:"widthFix"
      },{
        image:"/images/goods4-detail02.jpg",
        mode:"widthFix"
      }
    ],
      imgdeparameter:[{
        image:"/images/goods4-dpm01.jpg",
        mode:"widthFix"
      },{
        image:"/images/goods4-dpm02.jpg",
        mode:"widthFix"
      }]
    }
  ]
  }
})
